### PR TITLE
modify create

### PR DESCRIPTION
**Pull request by benjwg**
gotta `python manage.py migrate` first

test with:

`curl -H "Content-Type: application/json" -X POST -d '{"location":"cute","box":"4","specimens":[{"amnh_catalog_a": "baz", "amnh_catalog_b":"baz","field_no":16,"description":"oh yea"}]}' http://localhost:8000/v1/records/`

### CODE REVIEW

**Comment by tngzng** [comment]
this lgtm! is there a reason why you use diff get notation here?
`'description': specimen['description'],`
`'location': specimen.get('location')`

**Comment by benjwg** [comment]
description shoooould always be on a specimen, location not neccearilly @stephtzhang

**Comment by benjwg** [comment]
(super pseudo error handling - that way if you try and post a specimen without description it'll error out.

**Comment by tngzng** [comment]
cool :+1:

**Pull request merged**
